# Generated by Django 3.1.2 on 2020-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhprofiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magallenes',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='magallenes',
            name='datetime',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='magallenes',
            name='kindinfra',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='magallenes',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='magallenes',
            name='path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
